version: '3.7'

services:
  web:
    build: ./library_management/
    volumes:
      - ./library_management:/library_management
    env_file:
      - .env
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - ./library_management/static:/static
    ports:
      - "80:80"
    depends_on:
      - web

